#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const DEFAULT_HOME_LAT = 40.6706039;
const DEFAULT_HOME_LNG = -73.9782784;

function parseCoordinate(rawValue, name, min, max, fallback) {
  if (rawValue === undefined || rawValue === "") {
    return fallback;
  }

  const parsed = Number(rawValue);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    console.error(
      `${name} must be a number between ${min} and ${max}. Got: ${JSON.stringify(rawValue)}`
    );
    process.exit(1);
  }

  return parsed;
}

const apiKey = process.env.GOOGLE_MAPS_API_KEY || "";
const sheetUrl = process.env.SHEET_CSV_URL || "";
const homeLat = parseCoordinate(process.env.HOME_LAT, "HOME_LAT", -90, 90, DEFAULT_HOME_LAT);
const homeLng = parseCoordinate(process.env.HOME_LNG, "HOME_LNG", -180, 180, DEFAULT_HOME_LNG);

if (process.env.VERCEL && !apiKey) {
  console.error(
    "GOOGLE_MAPS_API_KEY is required. Add it in Vercel → Settings → Environment Variables."
  );
  process.exit(1);
}

const outputPath = path.join(__dirname, "..", "js", "config.js");
const contents = `// Generated by scripts/generate-config.js — do not edit on deploy.
window.KATES_KAFES_CONFIG = {
  GOOGLE_MAPS_API_KEY: ${JSON.stringify(apiKey)},
  SHEET_CSV_URL: ${JSON.stringify(sheetUrl)},
  HOME: { lat: ${homeLat}, lng: ${homeLng} },
};
`;

fs.writeFileSync(outputPath, contents, "utf8");
console.log("Wrote js/config.js");
