#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const apiKey = process.env.GOOGLE_MAPS_API_KEY || "";
const sheetUrl = process.env.SHEET_CSV_URL || "";
const homeLat = Number(process.env.HOME_LAT || "40.6706039");
const homeLng = Number(process.env.HOME_LNG || "-73.9782784");

if (process.env.VERCEL && !apiKey) {
  console.error(
    "GOOGLE_MAPS_API_KEY is required. Add it in Vercel → Settings → Environment Variables."
  );
  process.exit(1);
}

const outputPath = path.join(__dirname, "..", "js", "config.js");
const contents = `// Generated by scripts/generate-config.js — do not edit on deploy.
window.KATES_KAFES_CONFIG = {
  GOOGLE_MAPS_API_KEY: ${JSON.stringify(apiKey)},
  SHEET_CSV_URL: ${JSON.stringify(sheetUrl)},
  HOME: { lat: ${homeLat}, lng: ${homeLng} },
};
`;

fs.writeFileSync(outputPath, contents, "utf8");
console.log("Wrote js/config.js");
